from pathlib import Path

from forge.evaluations.materializer import validate_repository_template


def test_generated_bytecode_cannot_change_fixture_snapshot(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text("value = 1\n")
    before = validate_repository_template(tmp_path)
    cache = tmp_path / "__pycache__"
    cache.mkdir()
    (cache / "app.cpython-314.pyc").write_bytes(b"generated bytecode")
    assert validate_repository_template(tmp_path) == before
