"""initial

Revision ID: 20260821_0001
Revises:
Create Date: 2026-08-22 01:43:31.448797
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260821_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("credential_kind", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("csrf_hash", sa.String(length=64), nullable=True),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(credential_kind = 'bootstrap' AND actor_id IS NULL AND csrf_hash IS NULL AND idle_expires_at IS NULL AND absolute_expires_at IS NULL AND revoked_at IS NULL) OR (credential_kind = 'session' AND actor_id IS NOT NULL AND csrf_hash IS NOT NULL AND idle_expires_at IS NOT NULL AND absolute_expires_at IS NOT NULL AND used_at IS NULL)",
            name=op.f("ck_operator_sessions_credential_shape"),
        ),
        sa.CheckConstraint(
            "credential_kind IN ('bootstrap','session')",
            name=op.f("ck_operator_sessions_credential_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_operator_sessions_token_hash"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_path", sa.Text(), nullable=False),
        sa.Column("github_repository", sa.String(length=512), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("instructions_path", sa.Text(), nullable=True),
        sa.Column("current_policy_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id", "current_policy_version"],
            ["project_policy_versions.project_id", "project_policy_versions.version"],
            name="fk_projects_current_policy_version_project_policy_versions",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("canonical_path", name="uq_projects_canonical_path"),
        sa.UniqueConstraint("github_repository", name="uq_projects_github_repository"),
    )
    op.create_table(
        "project_policy_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy_digest", sa.String(length=64), nullable=False),
        sa.Column("document_schema_version", sa.Integer(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_policy_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "version", name=op.f("pk_project_policy_versions")),
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION forge_reject_project_policy_version_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $forge$
        BEGIN
            RAISE EXCEPTION 'project_policy_versions rows are immutable';
        END;
        $forge$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_project_policy_versions_immutable
        BEFORE UPDATE ON project_policy_versions
        FOR EACH ROW EXECUTE FUNCTION forge_reject_project_policy_version_update();
        """
    )
    op.create_foreign_key(
        "fk_projects_current_policy_version_project_policy_versions",
        "projects",
        "project_policy_versions",
        ["id", "current_policy_version"],
        ["project_id", "version"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("task_digest", sa.String(length=64), nullable=False),
        sa.Column("external_source", sa.String(length=64), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(external_source IS NULL) = (external_id IS NULL)",
            name=op.f("ck_tasks_external_identity_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tasks_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("external_source", "external_id", name="uq_tasks_external_identity"),
        sa.UniqueConstraint("id", "project_id", name="uq_tasks_id_project_id"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=48), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("suspended_state", sa.String(length=48), nullable=True),
        sa.Column("suspension_kind", sa.String(length=24), nullable=True),
        sa.Column("suspension_context_schema_version", sa.Integer(), nullable=True),
        sa.Column("suspension_context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("local_remediation_count", sa.Integer(), nullable=False),
        sa.Column("remote_remediation_count", sa.Integer(), nullable=False),
        sa.Column("token_budget", sa.Integer(), nullable=False),
        sa.Column("cost_budget_minor", sa.Integer(), nullable=False),
        sa.Column("duration_budget_seconds", sa.Integer(), nullable=False),
        sa.Column("worktree_path", sa.Text(), nullable=True),
        sa.Column("branch_name", sa.String(length=512), nullable=True),
        sa.Column("base_ref", sa.String(length=512), nullable=True),
        sa.Column("base_sha", sa.String(length=40), nullable=True),
        sa.Column("candidate_commit", sa.String(length=40), nullable=True),
        sa.Column("database_state", sa.String(length=24), nullable=False),
        sa.Column("database_name", sa.String(length=63), nullable=True),
        sa.Column("database_role", sa.String(length=63), nullable=True),
        sa.Column("secret_id", sa.String(length=512), nullable=True),
        sa.Column("pending_gate", sa.String(length=16), nullable=True),
        sa.Column("pending_evidence_digest", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(database_state IN ('DISABLED','REMOVED') AND database_name IS NULL AND database_role IS NULL AND secret_id IS NULL) OR database_state IN ('PROVISIONING','FAILED') OR (database_state = 'ACTIVE' AND database_name IS NOT NULL AND database_role IS NOT NULL AND secret_id IS NOT NULL)",
            name=op.f("ck_runs_database_resource_shape"),
        ),
        sa.CheckConstraint(
            "(state NOT IN ('AWAITING_PLAN_APPROVAL','AWAITING_PR_APPROVAL','AWAITING_MERGE_APPROVAL') AND pending_gate IS NULL AND pending_evidence_digest IS NULL) OR (state = 'AWAITING_PLAN_APPROVAL' AND pending_gate = 'plan' AND pending_evidence_digest IS NOT NULL) OR (state = 'AWAITING_PR_APPROVAL' AND pending_gate = 'pr' AND pending_evidence_digest IS NOT NULL) OR (state = 'AWAITING_MERGE_APPROVAL' AND pending_gate = 'merge' AND pending_evidence_digest IS NOT NULL)",
            name=op.f("ck_runs_pending_gate_shape"),
        ),
        sa.CheckConstraint(
            "database_state IN ('DISABLED','PROVISIONING','ACTIVE','FAILED','REMOVED')",
            name=op.f("ck_runs_database_state"),
        ),
        sa.CheckConstraint(
            "state IN ('CREATED','PLANNING','AWAITING_PLAN_APPROVAL','PREPARING_WORKTREE','IMPLEMENTING','VALIDATING','REVIEWING','REMEDIATING','AWAITING_PR_APPROVAL','PUBLISHING_PR','MONITORING_PR','AWAITING_HUMAN_INTERVENTION','INTERVENTION_REQUIRED','AWAITING_MERGE_APPROVAL','MERGING','PAUSED','COMPLETED','FAILED','CANCELLED')",
            name=op.f("ck_runs_state"),
        ),
        sa.CheckConstraint(
            "(state = 'PAUSED' AND suspended_state IS NOT NULL AND suspension_kind IS NOT NULL AND suspension_kind = 'PAUSE' AND suspension_context IS NOT NULL AND suspension_context_schema_version IS NOT NULL AND suspension_context_schema_version >= 1) OR (state IN ('INTERVENTION_REQUIRED','AWAITING_HUMAN_INTERVENTION') AND suspended_state IS NOT NULL AND suspension_kind IS NOT NULL AND suspension_kind = 'INTERVENTION' AND suspension_context IS NOT NULL AND suspension_context_schema_version IS NOT NULL AND suspension_context_schema_version >= 1) OR (state NOT IN ('PAUSED','INTERVENTION_REQUIRED','AWAITING_HUMAN_INTERVENTION') AND suspended_state IS NULL AND suspension_kind IS NULL AND suspension_context IS NULL AND suspension_context_schema_version IS NULL)",
            name=op.f("ck_runs_suspension_state_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "policy_version"],
            ["project_policy_versions.project_id", "project_policy_versions.version"],
            name="fk_runs_policy_version_project_policy_versions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id", "project_id"],
            ["tasks.id", "tasks.project_id"],
            name="fk_runs_task_project_tasks",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_project_id", "runs", ["project_id"], unique=False)
    op.create_index("ix_runs_state", "runs", ["state"], unique=False)
    op.create_index("ix_runs_updated_at", "runs", ["updated_at"], unique=False)
    op.create_table(
        "approval_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("gate", sa.String(length=16), nullable=False),
        sa.Column("run_version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("evidence_digest", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gate IN ('plan','pr','merge')", name=op.f("ck_approval_challenges_gate")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_approval_challenges_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["operator_sessions.id"],
            name=op.f("fk_approval_challenges_session_id_operator_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_challenges")),
        sa.UniqueConstraint("token_hash", name="uq_approval_challenges_token_hash"),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("gate", sa.String(length=16), nullable=False),
        sa.Column("evidence_digest", sa.String(length=64), nullable=False),
        sa.Column("run_version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("authenticated_actor_id", sa.Uuid(), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("gate IN ('plan','pr','merge')", name=op.f("ck_approvals_gate")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_approvals_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "run_id",
            "gate",
            "evidence_digest",
            "run_version",
            name="uq_approvals_gate_evidence_run_version",
        ),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("storage_pointer", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("producer_kind", sa.String(length=96), nullable=False),
        sa.Column("producer_id", sa.Uuid(), nullable=True),
        sa.Column("parent_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("metadata_schema_version", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_artifacts_parent_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_artifacts_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("digest", name="uq_artifacts_digest"),
    )
    op.create_table(
        "operation_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("operation_kind", sa.String(length=96), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_schema_version", sa.Integer(), nullable=False),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("provider_request_id", sa.String(length=512), nullable=True),
        sa.Column("repository_id", sa.String(length=512), nullable=True),
        sa.Column("resource_identity", sa.String(length=1024), nullable=True),
        sa.Column("outcome_schema_version", sa.Integer(), nullable=True),
        sa.Column("outcome_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','IN_PROGRESS','SUCCEEDED','FAILED','RECONCILING')",
            name=op.f("ck_operation_intents_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_operation_intents_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_intents")),
        sa.UniqueConstraint("idempotency_key", name="uq_operation_intents_idempotency_key"),
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("repository", sa.String(length=512), nullable=False),
        sa.Column("branch", sa.String(length=512), nullable=False),
        sa.Column("base_ref", sa.String(length=512), nullable=False),
        sa.Column("pull_request_number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=False),
        sa.Column("checks_schema_version", sa.Integer(), nullable=False),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviews_schema_version", sa.Integer(), nullable=False),
        sa.Column("reviews", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("merge_state", sa.String(length=48), nullable=True),
        sa.Column("merge_method", sa.String(length=24), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_pull_requests_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pull_requests")),
        sa.UniqueConstraint(
            "repository", "pull_request_number", name="uq_pull_requests_repository_number"
        ),
    )
    op.create_table(
        "run_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("command_type", sa.String(length=96), nullable=False),
        sa.Column("expected_run_version", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','LEASED','SUCCEEDED','FAILED','CANCELLED')",
            name=op.f("ck_run_commands_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_commands_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_commands")),
        sa.UniqueConstraint("idempotency_key", name="uq_run_commands_idempotency_key"),
    )
    op.create_index("ix_run_commands_available_at", "run_commands", ["available_at"], unique=False)
    op.create_index(
        "ix_run_commands_lease_expires_at", "run_commands", ["lease_expires_at"], unique=False
    )
    op.create_index("ix_run_commands_status", "run_commands", ["status"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("run_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("actor_class", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("payload_schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.CheckConstraint(
            "actor_class IN ('system','worker','agent','operator','unauthenticated')",
            name=op.f("ck_run_events_actor_class"),
        ),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_run_events_sequence_positive")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_events_run_sequence"),
    )
    op.create_index(
        "ix_run_events_run_id_sequence", "run_events", ["run_id", "sequence"], unique=False
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=96), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("transition_from", sa.String(length=48), nullable=True),
        sa.Column("transition_to", sa.String(length=48), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("output_artifact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED')",
            name=op.f("ck_steps_status"),
        ),
        sa.ForeignKeyConstraint(
            ["output_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_steps_output_artifact_id_artifacts"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_steps_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_steps")),
        sa.UniqueConstraint("run_id", "kind", "attempt", name="uq_steps_run_kind_attempt"),
    )
    op.create_foreign_key(
        "fk_steps_output_artifact_id_artifacts",
        "steps",
        "artifacts",
        ["output_artifact_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("instruction_version", sa.String(length=96), nullable=False),
        sa.Column("provider", sa.String(length=96), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("output_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('planner','developer','reviewer')", name=op.f("ck_agent_executions_role")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED')",
            name=op.f("ck_agent_executions_status"),
        ),
        sa.ForeignKeyConstraint(
            ["input_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_agent_executions_input_artifact_id_artifacts"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["output_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_agent_executions_output_artifact_id_artifacts"),
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_agent_executions_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_agent_executions_step_id_steps"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_executions")),
    )
    op.create_foreign_key(
        "fk_agent_executions_input_artifact_id_artifacts",
        "agent_executions",
        "artifacts",
        ["input_artifact_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_agent_executions_output_artifact_id_artifacts",
        "agent_executions",
        "artifacts",
        ["output_artifact_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("check_name", sa.String(length=255), nullable=False),
        sa.Column("command_name", sa.String(length=255), nullable=False),
        sa.Column("command_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("output_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["output_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_validation_results_output_artifact_id_artifacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_validation_results_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["steps.id"],
            name=op.f("fk_validation_results_step_id_steps"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_results")),
    )
    op.create_table(
        "model_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_execution_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=96), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_minor", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_model_usage_agent_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_model_usage_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_usage")),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("reviewer_execution_id", sa.Uuid(), nullable=True),
        sa.Column("finding_id", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("proposed_resolution", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('blocker','major','minor','suggestion')", name=op.f("ck_reviews_severity")
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_reviews_reviewer_execution_id_agent_executions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_reviews_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["step_id"], ["steps.id"], name=op.f("fk_reviews_step_id_steps"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("run_id", "finding_id", name="uq_reviews_run_finding_id"),
    )
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_execution_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments_schema_version", sa.Integer(), nullable=False),
        sa.Column("normalized_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("authorized", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("result_metadata_schema_version", sa.Integer(), nullable=True),
        sa.Column("result_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_tool_calls_agent_execution_id_agent_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_tool_calls_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
    )
    op.create_check_constraint(
        op.f("ck_project_policy_versions_version_positive"),
        "project_policy_versions",
        "version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_project_policy_versions_document_schema_version_positive"),
        "project_policy_versions",
        "document_schema_version >= 1",
    )
    op.create_check_constraint(op.f("ck_runs_version_nonnegative"), "runs", "version >= 0")
    op.create_check_constraint(
        op.f("ck_runs_remediation_counts_nonnegative"),
        "runs",
        "local_remediation_count >= 0 AND remote_remediation_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_runs_budgets_nonnegative"),
        "runs",
        "token_budget >= 0 AND cost_budget_minor >= 0 AND duration_budget_seconds >= 0",
    )
    op.create_check_constraint(
        op.f("ck_approval_challenges_versions"),
        "approval_challenges",
        "run_version >= 0 AND policy_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_run_commands_versions_and_attempts"),
        "run_commands",
        "expected_run_version >= 0 AND attempt_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_run_commands_payload_schema_version_positive"),
        "run_commands",
        "payload_schema_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_run_events_run_version_nonnegative"), "run_events", "run_version >= 0"
    )
    op.create_check_constraint(
        op.f("ck_run_events_payload_schema_version_positive"),
        "run_events",
        "payload_schema_version >= 1",
    )
    op.create_check_constraint(op.f("ck_steps_attempt_positive"), "steps", "attempt >= 1")
    op.create_check_constraint(
        op.f("ck_approvals_versions"),
        "approvals",
        "run_version >= 0 AND policy_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_tool_calls_status"),
        "tool_calls",
        "status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','DENIED','CANCELLED')",
    )
    op.create_check_constraint(
        op.f("ck_tool_calls_arguments_schema_version_positive"),
        "tool_calls",
        "arguments_schema_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_tool_calls_result_metadata_shape"),
        "tool_calls",
        "(result_metadata IS NULL AND result_metadata_schema_version IS NULL) OR "
        "(result_metadata IS NOT NULL AND result_metadata_schema_version >= 1)",
    )
    op.create_check_constraint(
        op.f("ck_model_usage_usage_nonnegative"),
        "model_usage",
        "input_tokens >= 0 AND output_tokens >= 0 AND estimated_cost_minor >= 0 "
        "AND latency_ms >= 0",
    )
    op.create_check_constraint(
        op.f("ck_artifacts_size_and_schema_version"),
        "artifacts",
        "size_bytes >= 0 AND metadata_schema_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_validation_results_status"),
        "validation_results",
        "status IN ('PENDING','RUNNING','PASSED','FAILED','SKIPPED','CANCELLED')",
    )
    op.create_check_constraint(
        op.f("ck_validation_results_command_version_positive"),
        "validation_results",
        "command_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_reviews_status"), "reviews", "status IN ('OPEN','RESOLVED','DISMISSED')"
    )
    op.create_check_constraint(
        op.f("ck_reviews_decision"),
        "reviews",
        "decision IS NULL OR decision IN ('PASS','FAIL')",
    )
    op.create_check_constraint(
        op.f("ck_reviews_start_line_positive"),
        "reviews",
        "start_line IS NULL OR start_line >= 1",
    )
    op.create_check_constraint(
        op.f("ck_operation_intents_attempt_count_nonnegative"),
        "operation_intents",
        "attempt_count >= 0",
    )
    op.create_check_constraint(
        op.f("ck_operation_intents_request_schema_version_positive"),
        "operation_intents",
        "request_schema_version >= 1",
    )
    op.create_check_constraint(
        op.f("ck_operation_intents_outcome_shape"),
        "operation_intents",
        "(outcome_payload IS NULL AND outcome_schema_version IS NULL) OR "
        "(outcome_payload IS NOT NULL AND outcome_schema_version >= 1)",
    )
    op.create_check_constraint(
        op.f("ck_pull_requests_number_positive"), "pull_requests", "pull_request_number >= 1"
    )
    op.create_check_constraint(
        op.f("ck_pull_requests_state"),
        "pull_requests",
        "state IN ('OPEN','CLOSED','MERGED')",
    )
    op.create_check_constraint(
        op.f("ck_pull_requests_merge_method"),
        "pull_requests",
        "merge_method IS NULL OR merge_method IN ('squash','merge','rebase')",
    )
    op.create_check_constraint(
        op.f("ck_pull_requests_payload_versions_positive"),
        "pull_requests",
        "checks_schema_version >= 1 AND reviews_schema_version >= 1",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_calls")
    op.drop_table("reviews")
    op.drop_table("model_usage")
    op.drop_table("validation_results")
    op.drop_constraint(
        "fk_agent_executions_output_artifact_id_artifacts",
        "agent_executions",
        type_="foreignkey",
        if_exists=True,
    )
    op.drop_constraint(
        "fk_agent_executions_input_artifact_id_artifacts",
        "agent_executions",
        type_="foreignkey",
        if_exists=True,
    )
    op.drop_table("agent_executions")
    op.drop_constraint(
        "fk_steps_output_artifact_id_artifacts",
        "steps",
        type_="foreignkey",
        if_exists=True,
    )
    op.drop_table("steps")
    op.drop_index("ix_run_events_run_id_sequence", table_name="run_events")
    op.drop_table("run_events")
    op.drop_index("ix_run_commands_status", table_name="run_commands")
    op.drop_index("ix_run_commands_lease_expires_at", table_name="run_commands")
    op.drop_index("ix_run_commands_available_at", table_name="run_commands")
    op.drop_table("run_commands")
    op.drop_table("pull_requests")
    op.drop_table("operation_intents")
    op.drop_table("artifacts")
    op.drop_table("approvals")
    op.drop_table("approval_challenges")
    op.drop_index("ix_runs_updated_at", table_name="runs")
    op.drop_index("ix_runs_state", table_name="runs")
    op.drop_index("ix_runs_project_id", table_name="runs")
    op.drop_table("runs")
    op.drop_table("tasks")
    op.drop_constraint(
        "fk_projects_current_policy_version_project_policy_versions",
        "projects",
        type_="foreignkey",
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_project_policy_versions_immutable ON project_policy_versions"
    )
    op.execute("DROP FUNCTION IF EXISTS forge_reject_project_policy_version_update()")
    op.drop_table("project_policy_versions")
    op.drop_table("projects")
    op.drop_table("operator_sessions")
    # ### end Alembic commands ###
